# coding: utf-8

"""
    Strava API v3

    Strava API  # noqa: E501

    OpenAPI spec version: 3.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import strava_api_v3
from strava_api_v3.models.running_race import RunningRace  # noqa: E501
from strava_api_v3.rest import ApiException


class TestRunningRace(unittest.TestCase):
    """RunningRace unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRunningRace(self):
        """Test RunningRace"""
        # FIXME: construct object with mandatory attributes with example values
        # model = strava_api_v3.models.running_race.RunningRace()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
