# coding: utf-8

"""
    Strava API v3

    Strava API  # noqa: E501

    OpenAPI spec version: 3.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import strava_api_v3
from strava_api_v3.api.running_races_api import RunningRacesApi  # noqa: E501
from strava_api_v3.rest import ApiException


class TestRunningRacesApi(unittest.TestCase):
    """RunningRacesApi unit test stubs"""

    def setUp(self):
        self.api = strava_api_v3.api.running_races_api.RunningRacesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_running_race_by_id(self):
        """Test case for get_running_race_by_id

        Get Running Race  # noqa: E501
        """
        pass

    def test_get_running_races(self):
        """Test case for get_running_races

        List Running Races  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
