# coding: utf-8

"""
    Strava API v3

    Strava API  # noqa: E501

    OpenAPI spec version: 3.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import strava_api_v3
from strava_api_v3.models.activity_zone import ActivityZone  # noqa: E501
from strava_api_v3.rest import ApiException


class TestActivityZone(unittest.TestCase):
    """ActivityZone unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testActivityZone(self):
        """Test ActivityZone"""
        # FIXME: construct object with mandatory attributes with example values
        # model = strava_api_v3.models.activity_zone.ActivityZone()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
