# coding: utf-8

"""
    Strava API v3

    Strava API  # noqa: E501

    OpenAPI spec version: 3.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import strava_api_v3
from strava_api_v3.models.summary_segment import SummarySegment  # noqa: E501
from strava_api_v3.rest import ApiException


class TestSummarySegment(unittest.TestCase):
    """SummarySegment unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSummarySegment(self):
        """Test SummarySegment"""
        # FIXME: construct object with mandatory attributes with example values
        # model = strava_api_v3.models.summary_segment.SummarySegment()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
