# coding: utf-8

"""
    Strava API v3

    Strava API  # noqa: E501

    OpenAPI spec version: 3.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import strava_api_v3
from strava_api_v3.api.clubs_api import ClubsApi  # noqa: E501
from strava_api_v3.rest import ApiException


class TestClubsApi(unittest.TestCase):
    """ClubsApi unit test stubs"""

    def setUp(self):
        self.api = strava_api_v3.api.clubs_api.ClubsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_club_activities_by_id(self):
        """Test case for get_club_activities_by_id

        List Club Activities  # noqa: E501
        """
        pass

    def test_get_club_admins_by_id(self):
        """Test case for get_club_admins_by_id

        List Club Administrators.  # noqa: E501
        """
        pass

    def test_get_club_by_id(self):
        """Test case for get_club_by_id

        Get Club  # noqa: E501
        """
        pass

    def test_get_club_members_by_id(self):
        """Test case for get_club_members_by_id

        List Club Members  # noqa: E501
        """
        pass

    def test_get_logged_in_athlete_clubs(self):
        """Test case for get_logged_in_athlete_clubs

        List Athlete Clubs  # noqa: E501
        """
        pass

    def test_join_club_by_id(self):
        """Test case for join_club_by_id

        Join Club  # noqa: E501
        """
        pass

    def test_leave_club_by_id(self):
        """Test case for leave_club_by_id

        Leave Club  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
