# coding: utf-8

"""
    Strava API v3

    Strava API  # noqa: E501

    OpenAPI spec version: 3.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import strava_api_v3
from strava_api_v3.api.routes_api import RoutesApi  # noqa: E501
from strava_api_v3.rest import ApiException


class TestRoutesApi(unittest.TestCase):
    """RoutesApi unit test stubs"""

    def setUp(self):
        self.api = strava_api_v3.api.routes_api.RoutesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_route_by_id(self):
        """Test case for get_route_by_id

        Get Route  # noqa: E501
        """
        pass

    def test_get_routes_by_athlete_id(self):
        """Test case for get_routes_by_athlete_id

        List Athlete Routes  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
