# coding: utf-8

"""
    Strava API v3

    Strava API  # noqa: E501

    OpenAPI spec version: 3.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import strava_api_v3
from strava_api_v3.models.distance_stream import DistanceStream  # noqa: E501
from strava_api_v3.rest import ApiException


class TestDistanceStream(unittest.TestCase):
    """DistanceStream unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDistanceStream(self):
        """Test DistanceStream"""
        # FIXME: construct object with mandatory attributes with example values
        # model = strava_api_v3.models.distance_stream.DistanceStream()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
